"use client";
import "./globals.css";
import Head from 'next/head';
import { Inter } from "next/font/google";
import { usePathname } from "next/navigation";
import styles from "./page.module.css";
import Footer from "./Footer";
import Header from "./Header";
import { useState } from "react";
const inter = Inter({ subsets: ["latin"] });

const metadata = {
  title: "Vatsal TV",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const router = usePathname();

  return (
    <html lang="en">
      <Head>
        <title>{metadata.title}</title>
        <meta name="description" content={metadata.description} />
      </Head>

      <body className={styles.className}>
        <Header />
        {children}
        <Footer pathname={router} />
      </body>
    </html>
  );
}
