"use client";
import "./globals.css";
import { Inter } from "next/font/google";
import { usePathname } from "next/navigation";
import styles from "./page.module.css";
import Footer from "./Footer";
import Header from "./Header";
import { useState } from "react";
const inter = Inter({ subsets: ["latin"] });

const metadata = {
  title: "Vatsal TV",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const router = usePathname();
  console.log("router", router);

  return (
    <html lang="en">
      <body className={styles.className}>
        <Header />
        {children}
        <Footer pathname={router} />
      </body>
    </html>
  );
}
