"use client"
import './globals.css'
import { Inter } from 'next/font/google'
import styles from './page.module.css'
import Footer from './Footer'
import Header from './Header' 
import { useState } from 'react'
const inter = Inter({ subsets: ['latin'] })

 const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}


export default function RootLayout({ children })
 {
  return (
    <html lang="en">
      <body className={styles.className}>
      <Header />
        {children}
      <Footer />
        </body>
    </html>
  )
}
